### ISSUE TITLE
Multiple beneficiaries

### ISSUE THREAD

**Issue by rainbreak** [MakerDAO/token-auction#1]
The two-way auction has a single beneficiary that receives bids in the forward part of the auction.

Maker would like to have multiple beneficiaries in the collateral auction so that it can reward keepers for liquidating CDPs, as well as sending funds to buy and burn.

The basic idea for implementing is to pass an array of `[[beneficiary, limit]]` to the auction initialiser. Each `beneficiary` receives funds up to their associated `limit`.

The auction still switches forward -> reverse at the `collection_limit`.

**Comment by rainbreak** [comment]
@nmushegian: for motivation can you describe some other use cases for this beyond collateral auction?

**Comment by nmushegian** [comment]
Liquidating a thing which has different share classes and other liquidation preference configurations
