### ISSUE TITLE
Allow further bids after auctionlet expired?

### ISSUE THREAD

**Issue by rainbreak** [MakerDAO/token-auction#12]
Merge of #11 means that auctionlets expire independently. 'Expiry' means that the time since the last bid is greater than `Auction.duration`. 

When an auctionlet has expired:
1. Further bids on the auctionlet are _not allowed_.
2. The high bidder can claim the auctionlet contents.

An alternative mechanism:
1. Further bids are _allowed_.
2. The high bidder can claim the auctionlet contents.

The meaning of auctionlet expiry changes from 'guaranteed-to-highest-bidder-on-claim' to 'can-be-claimed-by-highest-bidder'. If the auctionlet is bid on after expiry it just becomes a regular un-expired auctionlet.

**Comment by nmushegian** [comment]
I think the race to have to claim adds an unnecessary disincentive for bidding

**Comment by rainbreak** [comment]
That's where I'm leaning now I type it out.
