### ISSUE TITLE
Forward auction collection limit

### ISSUE THREAD

**Issue by rainbreak** [MakerDAO/token-auction#3]
The regular forward auction has an effectively infinite collection limit. That is, the beneficiary can receive up to `2 ** 256 - 1` of the auction buying token.

There may be a case for a non-infinite collection-limit in the forward auction, so that the beneficiaries rewards are capped at a given value. This would be equivalent to a two-way auction that ends, rather than transitioning to a reverse auction, when the limit is reached.

**Comment by nmushegian** [comment]
I think this is ok if you think of it as a max price instead of max quantity, because each individual auctionlet has to max out at the same price otherwise it behaves strangely. Not a high priority IMO.

**Comment by rainbreak** [comment]
You can do max quantity - just like the two-way auction, instead of transitioning you force expiry. Then all that bidders can do is `claim` on their won auctionlets.

**Comment by nmushegian** [comment]
> You can do max quantity

You _can_ but don't _want_ to - you want to use the price, otherwise it creates an incentive to race to try to create a ton of very small bids and hope someone else maxes out the limit.

**Comment by rainbreak** [comment]
Price is implicit in the limit: price = buy_token_quantity / sell_token_quantity.

The limit is set in terms of the buy_token. The minimum stopping price the auction gives is collection_limit / A.sell_amount - both of which are parameters controlled by the auction creator.

**Comment by nmushegian** [comment]
Is it implicitly defined and actually enforced, or are you still thinking it's actually implicit?

> The minimum stopping price the auction gives is collection_limit / A.sell_amoun

Ok, but this is enforced per-auctionlet, correct?

**Comment by nmushegian** [comment]
with the reverse auction you don't have this issue because once the limit is hit the too-low-price bids still have their _price_ bid up in the reverse phase, so the end result is all auctionlets close at roughly the market price

**Comment by rainbreak** [comment]
It is implicitly defined and actually enforced (well it would be if implemented). The 'price' here is an effective price over the whole auction. It doesn't matter how much each auctionlet actually goes for.

A.sell_amount is the total Auction sell amount, not per-auctionlet (they have their own a.sell_amount).

**Comment by rainbreak** [comment]
The two-way transition can be thought of as occurring at an effective price - A.collection_limit / A.sell_amount. This price is the minimum - it will be higher if the auction has been split and not all has been bid on.

And yes, a Keeper has an incentive to arbitrage across auctionlets.

**Comment by nmushegian** [comment]
> It doesn't matter how much each auctionlet actually goes for.

It really does...

Here's the pathological scenario:

sell 100 MKR and collect at most 100 ETH
- A bids 10 ETH for 1 MKR
- B bids 90 ETH for 99 MKR

Auction over! Go home everyone! No price was discovered here...

**Comment by rainbreak** [comment]
B gets refunded 9 ETH because their bid goes over the collection limit.

Total outcome: 10 + 90 = 100 ETH for 1 + 99 = 100 MKR, and auction terminated, as expected.

**Comment by nmushegian** [comment]
^ I edited it to say 90 instead of 99. Point is, the prices A and B paid are 10x apart. Maybe B got a steep discount because A was irrational - the auctioneer has to set a minimum to protect against people bidding _irrationally high_ - what?

**Comment by rainbreak** [comment]
Well that's A's problem right?

**Comment by nmushegian** [comment]
Also the auctioneer's problem, either his min bid was high enough to protect himself and he just has to restart it, or someone else gets a good price and closes the auction without other participants getting to outbid them

**Comment by nmushegian** [comment]
I think the solution is just enforcing a maximum _price_ for each auctionlet to match the original implied price

**Comment by rainbreak** [comment]
Well yeah, if the auctioneer didn't consider 100 ETH / 100 MKR to be a good deal then they shouldn't have created the auction in the first place.

I'm not really sure of the exact use-case of this issue.

**Comment by nmushegian** [comment]
digix-style crowdsale I guess. My opinion was that it was smart to cap collected fees but they should have used a two-way splitting auction instead =P

**Comment by rainbreak** [comment]
Haha agreed :)

I suppose the utility of this is that it gives a different expiry mechanism other than waiting for A.duration to pass. However, the beneficiary is continuously paid out as new bids come in anyway so it isn't like they need it to expire sooner.

Maybe it is attractive to bidders - a sort of 'buy it now' price for the full lot. If that is the attraction, then I agree with you that individual auctionlets should be expired if they are bid up to a target price.

**Comment by rainbreak** [comment]
Closing. Can re-open if we see a need.
