### ISSUE TITLE
throw on negative db lookup

### ISSUE THREAD

**Issue by rainbreak** [MakerDAO/token-auction#38]
Lookup of a non-existent auction(let) should throw, rather than returning a null entry.

Argument against this is that current tooling means users don't know why the throw was raised.

**Comment by rainbreak** [comment]
This contract uses assertions liberally, throwing on invalid function calls, so the frontend needs to model the contract state anyway if it wants to give descriptive errors to users.

Because of this I think it would be consistent to throw on null db lookup as well - the frontend would be modelling the existing auction(let)s by listening to the event stream.

**Comment by rainbreak** [comment]
@jorisbontje @freek I'm like to put this in at some point. I can either do it now or defer for a bit - which is less friction for you?

**Comment by rainbreak** [comment]
Note that this is already sort of present in `assertBiddable`:

```
        assert(auctionlet.auction_id > 0);  // test for deleted auction
        assert(auctionlet_id > 0);  // test for deleted auctionlet
```

So the question is whether to throw on _any_ null db lookup.

**Comment by jorisbontje** [comment]
@rainbeam do it now!
