### ISSUE TITLE
Frontend for token-auction

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/token-auction#4]
Following nikolai's suggestion in #trading, maybe a good first auction project would be a ui for a weekly mkr auction?
This has a few benefits:
- contained project. Just implement the forward auction at first.
- low system risk. Only smallish amount of MKR goes in each week (I'm guessing 50-100MKR).
- field test the auction contract. Despite low system risk there is still an incentive to try and break the contract.
- easy to upgrade. Can switch the contract on weekly auction expiry (I expect there to be backend changes as I integrate with Maker).
- Work out ui snags before working on the 'real' Maker liquidation auctions.
- presents a target for a keeper task. This can be written afterward as a demo of linking the market and auctions.

The auction would have a single beneficiary: the maker fund.

**Comment by rainbreak** [comment]
Weekly auction frontend: https://github.com/MakerDAO/weekly-mkr-auction

**Comment by jorisbontje** [comment]
closing as this project is tracked on https://waffle.io/MakerDAO/weekly-mkr-auction
