### ISSUE TITLE
bids strictly increase, even for small tokens

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/token-auction#42]
regarding https://github.com/makerdao/token-auction/commit/dab6b6014c8b20c41996ed730a6186113d3be7ce

This means that if I have an auction of 1.00 MKR with starting bid of 1.00 MKR and 1% min_increase; you have to bid MORE than 1.01 ETH.

The `min_increase` does already / enforce a minimum increase; so this could be `>=` as assertion condition in the case where `min_increase` is set. For the case where `min_increase` is zero, I suggest to add`assert(bid_how_much > a.buy_amount);`

**Comment by rainbreak** [comment]
Random thought: another way of setting the bid delta is to provide `(u, v)` of `b' = u + vb`. This would allow for both relative and absolute increase.
