### ISSUE TITLE
Specify refund address in two-way auction

### ISSUE THREAD

**Issue by rainbreak** [MakerDAO/token-auction#5]
Excess selling token in the two-way auction is refunded to the creator.

This should be configurable (motivation: refunding a liquidated cdp owner directly).

**Comment by rainbreak** [comment]
There are two cases in which there is excess sell-token:
1. In the forward part of the auction, if the full lot is not bid on.
2. In the reverse part of the auction, as the lowest bid drops.

We want to return the excess in the 2nd case to the cdp owner. Excess collateral in the 1st case belongs to Maker, but where should it be sent to (if all auctionlets expire)?

**Comment by nmushegian** [comment]
Auctionlets with no bids don't expire, so refund 1) never happens

**Comment by rainbeam** [comment]
All tests passing.
