### ISSUE TITLE
Auction duration

### ISSUE THREAD

**Issue by rainbreak** [MakerDAO/token-auction#6]
Presently, auctions have a specific expiration point given by their starting duration. All auctionlets end at the same time as their parent auction.

Other strategies to think about:
- Independent auctionlet expirations, possibly with an absolute maximum auction length.
- Unpredictable expirations - e.g. normal distribution around the set expiration. This would discourage sniping and promote rapid price discovery.

**Comment by nmushegian** [comment]
Expiration should be independent per auctionlet. "Duration" is more like "how long to wait before the last bid is finalized".

**Comment by rainbreak** [comment]
That was my original design, but changed to global auction expiry time for simplicity. Will implement per auctionlet.

Is there a case for a global maximum auction duration? So that you know auctions won't go on for longer than given length.

**Comment by nmushegian** [comment]
Relative minimum bids ensure auctions end soon enough. Later, we could think about smarter ways of increasing the duration besides just resetting it each time.
