### ISSUE TITLE
force typing of bid values

### ISSUE THREAD

**Issue by rainbreak** [MakerDAO/token-auction#7]
Bids are made like `bid(auction_id, bid_how_much)`.

This could be changed to `bid(auction_id, bid_how_much, bid_which_token)` to force the user to specify the token they think they are bidding on, which can then be checked.

This is more of an issue in two way auctions, where the bidding token flips on reversal - we may want to ensure that users are aware of that, beyond expecting them to listen for the `Reversal` event.

**Comment by nmushegian** [comment]
seems unecessary, users going around the UI should know what they are getting into. In two way auction, I'd think the two directions would have separate functions, but I don't think that matters much either

**Comment by rainbreak** [comment]
Actually in the two-way auction it's the same function - `bid`. Bidders have to watch out for a `Reversal` event to know when the context changes.

Should probably provide an `isReversed` method to make it easy to check.

**Comment by nmushegian** [comment]
But why is it the same function? You're adding 32 bytes to communicate something implicitly, instead of changing 8 bytes (function signature) to communicate it explicitly

**Comment by rainbreak** [comment]
Good point. So we'd have `bid` and `bidReverse`. Will keep status quo for now.

**Comment by rainbreak** [comment]
Can re-open if actually a problem.
